services:
  app:
    build:
      context: .
    ports:
     - "8080:2704"
    volumes:
      -./app.py:app/app.py
      -./regression.joblib:app/regression.joblib
      -./requirements.txt:app/requirements.txt
