name: Docker deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t mlops-exo-1:latest .

      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Tag Docker image
        run: docker tag mlops-exo-1:latest ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-exo-1:latest

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-exo-1:latest

      - name: Connect to the VM with SSH
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ubuntu@${{ secrets.SSH_HOST }} -o StrictHostKeyChecking=no << 'EOF'
            if [ ! -d "/home/ubuntu/emile.merle" ]; then
              mkdir /home/ubuntu/emile.merle
            fi
            cd /home/ubuntu/emile.merle
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-exo-1:latest
            docker stop emile-mlops || true
            docker run -d -p 2704:2704 --name emile-mlops ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-exo-1:latest
          EOF